name: "Boxes"
genesis_accounts: 10000
genesis_account_balance: 1000000000000
tx_per_block: 5000

# transactions that occur at the top of the first block
priming_txns:
  - create_box_app_txn
  - fund_box_app_txn

# transaction distribution
tx_pay_fraction: 0.1
tx_asset_fraction: 0.1
tx_box_app_fraction: 0.8

# payment config
pay_acct_create_fraction: 0.02
pay_xfer_fraction: 0.98

# asset config
asset_create_fraction: 0.001
asset_optin_fraction: 0.1
asset_close_fraction: 0.05
asset_xfer_fraction: 0.849
asset_delete_fraction: 0

# box app config
box_app_create_fraction: 0.25  # test that creates max-size box (of size 64 * 2^9)
box_app_fill_fraction: 0.25    # test that fills a box with its own name
box_app_log_fraction: 0.5     # test that reads and logs full box contents